# -*- coding: utf-8 -*-
"""day4unsupervise.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1b4LaV4m3HHwlGdBfWLnI2flI62Zvg4ij
"""

import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

data=pd.read_csv('/content/Mall_Customers.csv')
data.head()

#checking for missing values
data.isna().sum()

"""outlier"""

data['CustomerID'].nunique()

plt.boxplot(data['Age'])
plt.title('box plot of Age')
plt.show()

plt.boxplot(data['Annual Income (k$)'])
plt.title('box plot of Annual Income (k$)')
plt.show()

Q1=np.percentile(data['Annual Income (k$)'],25)
Q2=np.percentile(data['Annual Income (k$)'],50)
Q3=np.percentile(data['Annual Income (k$)'],75)
print(Q1)
print(Q2)
print(Q3)

data['Annual Income (k$)'].median()

IQR=Q3-Q1
print(IQR)

up_lim=Q3+1.5*IQR
low_lim=Q1-1.5*IQR
print(up_lim)
print(low_lim)

outlier=[]
for i in data['Annual Income (k$)']:
  if i>up_lim or i<low_lim:
    outlier.append(i)
outlier

#labelencoding
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()

# encoding Annual income (k$) using binary encoding
data["Genre"] = le.fit_transform(data["Genre"])
data.head()

x=data.drop('CustomerID',axis=1)

from sklearn.cluster import KMeans

wcss=[]
for i in range(1,11):
  kmeans= KMeans(n_clusters=i,init='k-means++',random_state=42,n_init=10)
  kmeans.fit(x)
  wcss.append(kmeans.inertia_)

wcss

plt.plot(range(1,11),wcss)
plt.title('the elbow method')
plt.xlabel('number of clusters')
plt.ylabel('wcss')
plt.grid()
plt.show()

km=KMeans(n_clusters=5,n_init=10)
km.fit(x)
cluster_labels=km.predict(x)

cluster_labels

scatter=plt.scatter(x['Annual Income (k$)'],
                    x['Spending Score (1-100)'],c=cluster_labels)
plt.xlabel('Annual Income (k$)')
plt.ylabel('Spending score (1-100)')
plt.title('Annual income vs spending score')
plt.legend(*scatter.legend_elements(),title="Clusters")
plt.show()

#function to predic cluster for a new customer
def predict_cluster(Genre,age,Annual_income,spending_score):
  new_data=[[Genre,age,Annual_income,spending_score]]
  cluster=km.predict(new_data)
  return cluster[0]

#example
new_customer_income=50
new_customer_spending_score=100
Genre='Male'
Genre=1 if Genre=='Male' else 0
age=25

predict_cluster=predict_cluster(
    Genre,
    age,
    new_customer_income,
    new_customer_spending_score
)
print(f'The custome belongs to custer: {predict_cluster}')

