# -*- coding: utf-8 -*-
"""classification.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10WNkoyGX96hiROCaR1dJ7-8ylqdn1u9Q
"""

import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

ads_data=pd.read_csv('/content/Social_Network_Ads.csv')
ads_data.head()

ads_data.shape

ads_data.columns

ads_data['User ID'].nunique()

#dropping user id column since all the values are unique
ads_data.drop('User ID',axis=1,inplace=True)
ads_data.head()

#checking for missing values
ads_data.isna().sum()

ads_data.dtypes

ads_data['Gender'].nunique()

ads_data.head()

#since 2 unique value we do one hot encoding gender column
ads_data=pd.get_dummies(ads_data,prefix='Gender',dtype=int)
ads_data.head()

ads_data['Purchased'].value_counts()

ads_data['Purchased'].value_counts(normalize=True)

"""Since number of 0 and 1 are no same,we call this as an imbalanced data"""

#checking outliers in numerical columns
plt.boxplot(ads_data['Age'])
plt.title('Boxplot of age column')
plt.show()

plt.boxplot(ads_data['EstimatedSalary'])
plt.title('Boxplot of Estimated Salary')

plt.show()

#feature - target splitting
y=ads_data['Purchased']
X=ads_data.drop('Purchased',axis=1)

#train - test split
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)

#Logistic Regreddion model
from sklearn.linear_model import LogisticRegression

lr_model=LogisticRegression(max_iter=1000)
lr_model.fit(X_train,y_train)
y_pred_lr_model=lr_model.predict(X_test)

from sklearn.metrics import confusion_matrix,precision_score,recall_score
from sklearn.metrics import accuracy_score,f1_score

print(confusion_matrix(y_test,y_pred_lr_model))
print(accuracy_score(y_test,y_pred_lr_model))
print(precision_score(y_test,y_pred_lr_model))
print(recall_score(y_test,y_pred_lr_model))
print(f1_score(y_test,y_pred_lr_model))

#knn
#finding the optimum k value
from sklearn.neighbors import KNeighborsClassifier
acc_score=[]
for k in range(3,10):
  knn=KNeighborsClassifier(n_neighbors=k)
  knn.fit(X_train,y_train)
  y_pred_knn=knn.predict(X_test)
  acc=accuracy_score(y_test,y_pred_knn)
  acc_score.append(acc)

acc_score

plt.plot(np.arange(3,10),acc_score,'o-')
plt.xlabel('K value')
plt.ylabel('Accuracy Score')
plt.grid()

# optimum k value =5 because accuracy is highest when k=5
#train the knn model fork=5
knn=KNeighborsClassifier(n_neighbors=5)
knn.fit(X_train,y_train)
y_pred_knn=knn.predict(X_test)
print(confusion_matrix(y_test,y_pred_knn))
print(accuracy_score(y_test,y_pred_knn))
print(precision_score(y_test,y_pred_knn))
print(recall_score(y_test,y_pred_knn))
print(f1_score(y_test,y_pred_knn))

X.describe()

#do scaling on numerical features
X1=X.copy()
from sklearn.preprocessing import MinMaxScaler
scaler=MinMaxScaler()

for i in['Age','EstimatedSalary']:
  X1[i]=scaler.fit_transform(X1[[i]])
X1.describe()

#train - test split for scaled data
X_train1,X_test1,y_train,y_test=train_test_split(X1,y,test_size=0.2,random_state=42)

#logistic regression model with scaled data
lr_model_scaled=LogisticRegression(max_iter=1000)
lr_model_scaled.fit(X_train1,y_train)
y_pred_lr_model_scaled=lr_model_scaled.predict(X_test1)

#logistic regression model with scaled data
print(confusion_matrix(y_test,y_pred_lr_model_scaled))
print(accuracy_score(y_test,y_pred_lr_model_scaled))
print(precision_score(y_test,y_pred_lr_model_scaled))
print(recall_score(y_test,y_pred_lr_model_scaled))
print(f1_score(y_test,y_pred_lr_model_scaled))

#knn model with scaled data
#finding optimum k value for optimum data
acc_score=[]
for k in range(3,10):
  knn_scaled=KNeighborsClassifier(n_neighbors=k)
  knn_scaled.fit(X_train1,y_train)
  y_pred_knn_scaled=knn_scaled.predict(X_test1)
  acc=accuracy_score(y_test,y_pred_knn_scaled)
  acc_score.append(acc)

plt.plot(np.arange(3,10),acc_score,'o-')
plt.xlabel('K value')
plt.ylabel('Accuracy Score')
plt.grid()

# optimum k value =6 because accuracy is highest when k=6
#train the knn_scaled model fork=6
knn_scaled=KNeighborsClassifier(n_neighbors=6)
knn_scaled.fit(X_train1,y_train)
y_pred_knn_scaled=knn_scaled.predict(X_test1)
print(confusion_matrix(y_test,y_pred_knn_scaled))
print(accuracy_score(y_test,y_pred_knn_scaled))
print(precision_score(y_test,y_pred_knn_scaled))
print(recall_score(y_test,y_pred_knn_scaled))
print(f1_score(y_test,y_pred_knn_scaled))

# SVM
from sklearn.svm import SVC

svmclf_linear=SVC(kernel='linear')
svmclf_linear.fit(X_train,y_train)
y_pred_svmclf_linear=svmclf_linear.predict(X_test)
print(confusion_matrix(y_test,y_pred_svmclf_linear))
print(accuracy_score(y_test,y_pred_svmclf_linear))
print(precision_score(y_test,y_pred_svmclf_linear))
print(recall_score(y_test,y_pred_svmclf_linear))
print(f1_score(y_test,y_pred_svmclf_linear))

#polynomial kernel
svmclf_poly=SVC(kernel='poly')
svmclf_poly.fit(X_train,y_train)
y_pred_svmclf_poly=svmclf_poly.predict(X_test)
print(confusion_matrix(y_test,y_pred_svmclf_poly))
print(accuracy_score(y_test,y_pred_svmclf_poly))
print(precision_score(y_test,y_pred_svmclf_poly))
print(recall_score(y_test,y_pred_svmclf_poly))
print(f1_score(y_test,y_pred_svmclf_poly))

#RBF Kernel
#polynomial kernel
svmclf_rbf=SVC(kernel='rbf')
svmclf_rbf.fit(X_train,y_train)
y_pred_svmclf_rbf=svmclf_rbf.predict(X_test)
print(confusion_matrix(y_test,y_pred_svmclf_rbf))
print(accuracy_score(y_test,y_pred_svmclf_rbf))
print(precision_score(y_test,y_pred_svmclf_rbf))
print(recall_score(y_test,y_pred_svmclf_rbf))
print(f1_score(y_test,y_pred_svmclf_rbf))

#scale linear
svmclf_linear_scale=SVC(kernel='linear')
svmclf_linear_scale.fit(X_train1,y_train)
y_pred_svmclf_linear_scale=svmclf_linear_scale.predict(X_test1)
print(confusion_matrix(y_test,y_pred_svmclf_linear_scale))
print(accuracy_score(y_test,y_pred_svmclf_linear_scale))
print(precision_score(y_test,y_pred_svmclf_linear_scale))
print(recall_score(y_test,y_pred_svmclf_linear_scale))
print(f1_score(y_test,y_pred_svmclf_linear_scale))

#polynomial kernel scale
svmclf_poly_scale=SVC(kernel='poly')
svmclf_poly_scale.fit(X_train1,y_train)
y_pred_svmclf_poly_scale=svmclf_poly_scale.predict(X_test1)
print(confusion_matrix(y_test,y_pred_svmclf_poly_scale))
print(accuracy_score(y_test,y_pred_svmclf_poly_scale))
print(precision_score(y_test,y_pred_svmclf_poly_scale))
print(recall_score(y_test,y_pred_svmclf_poly_scale))
print(f1_score(y_test,y_pred_svmclf_poly_scale))

#RBF Kernel scale
#polynomial kernel
svmclf_rbf_scale=SVC(kernel='rbf')
svmclf_rbf_scale.fit(X_train1,y_train)
y_pred_svmclf_rbf_scale=svmclf_rbf_scale.predict(X_test1)
print(confusion_matrix(y_test,y_pred_svmclf_rbf_scale))
print(accuracy_score(y_test,y_pred_svmclf_rbf_scale))
print(precision_score(y_test,y_pred_svmclf_rbf_scale))
print(recall_score(y_test,y_pred_svmclf_rbf_scale))
print(f1_score(y_test,y_pred_svmclf_rbf_scale))

#Decision trees
from sklearn.tree import DecisionTreeClassifier
dt_clf=DecisionTreeClassifier(criterion='entropy')
dt_clf.fit(X_train,y_train)
y_pred_dt=dt_clf.predict(X_test)
print(confusion_matrix(y_test,y_pred_dt))
print(accuracy_score(y_test,y_pred_dt))
print(precision_score(y_test,y_pred_dt))
print(recall_score(y_test,y_pred_dt))
print(f1_score(y_test,y_pred_dt))

#random Forest
from sklearn.ensemble import RandomForestClassifier
rt_clf=RandomForestClassifier()
rt_clf.fit(X_train,y_train)
y_pred_rt=rt_clf.predict(X_test)
print(confusion_matrix(y_test,y_pred_rt))
print(accuracy_score(y_test,y_pred_rt))
print(precision_score(y_test,y_pred_rt))
print(recall_score(y_test,y_pred_rt))
print(f1_score(y_test,y_pred_rt))

