# -*- coding: utf-8 -*-
"""Beer_servings_regression.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zuPC0OL8qTv4Uqc8b8O9IJP39poJzCiD
"""

import numpy as np #for numerical operation
import pandas as pd #for datasets
import seaborn as sns
import matplotlib.pyplot as plt #for visualization

data= pd.read_csv("/content/beer-servings.csv")#to load data set
data.head()#for display 1st 5 row

data.head(10)#for display 1st 10 row

data.tail()#for dis last 5 row

data.tail(10)

data.columns

data.shape#for getting row x column

data.dtypes

data.info()

data.describe()

"""### Visualize distribution of numerical features"""

numerical_cols = data.select_dtypes(include=['float64', 'int64']).columns

plt.figure(figsize=(15, 10))
for i, col in enumerate(numerical_cols):
    plt.subplot(3, 3, i + 1) # Adjust subplot grid as needed
    sns.histplot(data[col].dropna(), kde=True)
    plt.title(f'Distribution of {col}')
    plt.xlabel(col)
    plt.ylabel('Frequency')
plt.tight_layout()
plt.show()

"""From the histograms, it appears that `beer_servings`, `spirit_servings`, `wine_servings`, and `total_litres_of_pure_alcohol` are right-skewed. The `Unnamed: 0` column is just an index and doesn't need transformation. Let's apply a log transformation to the skewed features to normalize them."""

skewed_cols = ['beer_servings', 'spirit_servings', 'wine_servings', 'total_litres_of_pure_alcohol']

for col in skewed_cols:
    # Add a small constant to avoid log(0) if there are zero values
    data[col] = np.log1p(data[col])

print("Distributions after log transformation:")
plt.figure(figsize=(15, 10))
for i, col in enumerate(skewed_cols):
    plt.subplot(2, 2, i + 1)
    sns.histplot(data[col].dropna(), kde=True)
    plt.title(f'Distribution of {col} (Log Transformed)')
    plt.xlabel(col)
    plt.ylabel('Frequency')
plt.tight_layout()
plt.show()

data.isna().sum()

plt.hist(data['beer_servings'])
plt.title('Distribution of Beer Servings')
plt.show()#dis al the open graph

data['beer_servings']=data['beer_servings'].fillna(data['beer_servings'].median())

plt.hist(data['beer_servings'])
plt.title('Distribution of Beer Servings')
plt.show()

data.isna().sum()

plt.hist(data['spirit_servings'])
plt.title('Distribution of spirit Servings')
plt.show()

data['spirit_servings']=data['spirit_servings'].fillna(data['spirit_servings'].median())

plt.hist(data['spirit_servings'])
plt.title('Distribution of spirit Servings')
plt.show()

data.isna().sum()

plt.hist(data['wine_servings'])
plt.title('Distribution of wine Servings')
plt.show()

data['wine_servings']=data['wine_servings'].fillna(data['wine_servings'].median())

plt.hist(data['wine_servings'])
plt.title('Distribution of wine Servings')
plt.show()

plt.hist(data['total_litres_of_pure_alcohol'])
plt.title('Distribution of total_litres_of_pure_alcohol')
plt.show()

data['total_litres_of_pure_alcohol']=data['total_litres_of_pure_alcohol'].fillna(data['total_litres_of_pure_alcohol'].median())

plt.hist(data['total_litres_of_pure_alcohol'])
plt.title('Distribution of total_litres_of_pure_alcohol')
plt.show()

data.isna().sum()

data.info()

"""to check outlier"""

plt.boxplot(data['beer_servings'])
plt.title('box plot of ear serving column')
plt.show()

plt.boxplot(data['spirit_servings'])
plt.title('spirit of ear serving column')
plt.show()

plt.boxplot(data['wine_servings'])
plt.title('wine of ear serving column')
plt.show()

plt.boxplot(data['beer_servings'])
plt.title('box plot of ear serving column')
plt.show()

plt.boxplot(data['spirit_servings'])
plt.title('spirit of ear serving column')
plt.show()

Q1=np.percentile(data['spirit_servings'],25)
Q2=np.percentile(data['spirit_servings'],50)
Q3=np.percentile(data['spirit_servings'],75)
print(Q1)
print(Q2)
print(Q3)

data['spirit_servings'].median()

IQR=Q3-Q1
print(IQR)

up_lim=Q3+1.5*IQR
low_lim=Q1-1.5*IQR
print(up_lim)
print(low_lim)

outlier=[]
for i in data['spirit_servings']:
  if i>up_lim or i<low_lim:
    outlier.append(i)
outlier

#wine
plt.boxplot(data['wine_servings'])
plt.title('wine of ear serving column')
plt.show()

Q1=np.percentile(data['wine_servings'],25)
Q2=np.percentile(data['wine_servings'],50)
Q3=np.percentile(data['wine_servings'],75)
print(Q1)
print(Q2)
print(Q3)

IQR=Q3-Q1
print(IQR)

up_lim=Q3+1.5*IQR
low_lim=Q1-1.5*IQR
print(up_lim)
print(low_lim)

outlier1=[]
for i in data['wine_servings']:
  if i>up_lim or i<low_lim:
    outlier1.append(i)
print(outlier1)

"""Encoding"""

#labelencoding
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()

data['country']=le.fit_transform(data['country'])
data.head()

#one hot encoding continent column

data=pd.get_dummies(data,dtype=int)
data.head()

data.shape

#remove unnamed: 0 and country columns
#Create a linear regression model with total litres of pure alcoo; a target

data.drop(['Unnamed: 0', 'country'], axis=1,inplace=True)

# Features (X) and Target (y)
X = data.drop('total_litres_of_pure_alcohol', axis=1)
y = data['total_litres_of_pure_alcohol']

# Split the dataset
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

X_test

# Create Linear Regression model
from sklearn.linear_model import LinearRegression
lr = LinearRegression()

model=lr.fit(X_train,y_train)

# Train the model
model.fit(X_train, y_train)

# Predictions
y_pred = model.predict(X_test)
print(y_pred)
print(y_test)

# Model accuracy
from sklearn.metrics import mean_squared_error,r2_score
print("R2 Score:", r2_score(y_test, y_pred))

